import 'styles/globals.css'
import { Inter } from 'next/font/google'
import Footer from "components/Footer";
import Header from "components/Header";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Architects Adrian',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
